name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        username: omulimisa
        host: 170.187.156.185
        port: 2299
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /usr/share/nginx/html/github_runner && sudo chmod +x server_deploy.sh && ./server_deploy.sh'
